// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsAuthenticated() {
  return window['go']['main']['AuthService']['IsAuthenticated']();
}

export function Login(arg1) {
  return window['go']['main']['AuthService']['Login'](arg1);
}

export function RefreshSession() {
  return window['go']['main']['AuthService']['RefreshSession']();
}

export function Whoami(arg1) {
  return window['go']['main']['AuthService']['Whoami'](arg1);
}
