// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function IsAuthenticated():Promise<boolean>;

export function Login(arg1:string):Promise<void>;

export function RefreshSession():Promise<void>;

export function Whoami(arg1:boolean):Promise<main.Auth>;
