// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsIndexing() {
  return window['go']['main']['IndexService']['IsIndexing']();
}

export function Refresh(arg1) {
  return window['go']['main']['IndexService']['Refresh'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['IndexService']['SetContext'](arg1);
}
