// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsIndexing():Promise<boolean>;

export function Refresh(arg1:number):Promise<void>;
