// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {io} from '../models';

export function Clear():Promise<void>;

export function Close():Promise<void>;

export function GetEntries():Promise<Array<main.LogEntry>>;

export function GetEntriesByLevel(arg1:string):Promise<Array<main.LogEntry>>;

export function GetLevel():Promise<string>;

export function GetMultiWriter():Promise<io.Writer>;

export function GetWriter():Promise<io.Writer>;

export function Initialize():Promise<void>;

export function SetLevel(arg1:string):Promise<void>;
