// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear() {
  return window['go']['main']['LogService']['Clear']();
}

export function Close() {
  return window['go']['main']['LogService']['Close']();
}

export function GetEntries() {
  return window['go']['main']['LogService']['GetEntries']();
}

export function GetEntriesByLevel(arg1) {
  return window['go']['main']['LogService']['GetEntriesByLevel'](arg1);
}

export function GetLevel() {
  return window['go']['main']['LogService']['GetLevel']();
}

export function GetMultiWriter() {
  return window['go']['main']['LogService']['GetMultiWriter']();
}

export function GetWriter() {
  return window['go']['main']['LogService']['GetWriter']();
}

export function Initialize() {
  return window['go']['main']['LogService']['Initialize']();
}

export function SetLevel(arg1) {
  return window['go']['main']['LogService']['SetLevel'](arg1);
}
