// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CountPosts():Promise<number>;

export function Search(arg1:string,arg2:string):Promise<Array<main.SearchResult>>;
