// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountPosts() {
  return window['go']['main']['SearchService']['CountPosts']();
}

export function Search(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['SearchService']['Search'](arg1, arg2, arg3, arg4, arg5);
}
