// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CountPosts():Promise<number>;

export function Search(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<main.SearchPage>;
